"""empty message

Revision ID: 725f29ff1189
Revises: ca3dbf441162
Create Date: 2021-11-16 20:55:00.598635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725f29ff1189'
down_revision = 'ca3dbf441162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
