"""empty message

Revision ID: 9b3b58ac0654
Revises: 
Create Date: 2021-11-15 09:23:50.482359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3b58ac0654'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moves',
    sa.Column('MoveId', sa.Integer(), nullable=False),
    sa.Column('MoveName', sa.String(length=20), nullable=False),
    sa.Column('effects', sa.String(length=20), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('stat_changes', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('MoveId'),
    sa.UniqueConstraint('MoveId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    # ### end Alembic commands ###
