"""empty message

Revision ID: afd7f932069f
Revises: 725f29ff1189
Create Date: 2021-11-23 08:55:35.378503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd7f932069f'
down_revision = '725f29ff1189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('LocationId', sa.Integer(), nullable=False),
    sa.Column('LocationName', sa.String(length=30), nullable=False),
    sa.Column('Effects', sa.String(length=30), nullable=True),
    sa.Column('SpawnId', sa.Integer(), nullable=False),
    sa.Column('FKPokemonId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('LocationId'),
    sa.UniqueConstraint('LocationId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    # ### end Alembic commands ###
