"""empty message

Revision ID: c02ab757a349
Revises: 
Create Date: 2021-11-15 06:38:49.645589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02ab757a349'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'moves', ['MoveId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moves', type_='unique')
    # ### end Alembic commands ###
