"""empty message

Revision ID: f5950798e2a1
Revises: afd7f932069f
Create Date: 2021-11-25 08:58:05.517462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5950798e2a1'
down_revision = 'afd7f932069f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'location', ['LocationId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='unique')
    # ### end Alembic commands ###
